version: '3.8'

services:
  imgapi:
    build: .
    container_name: imgapi
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 挂载配置文件
      - ./config.yaml:/app/config.yaml:ro
    environment:
      # 可以通过环境变量覆盖配置
      - GIN_MODE=release
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/getinfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s