name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        default: 'v1.0.0'

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get last release tag
      id: previous_release
      run: |
        git fetch --tags
        LAST_TAG=$(git tag --sort=-creatordate | head -n 1)
        echo "last_tag=$LAST_TAG" >> $GITHUB_ENV

    - name: Get commit messages
      id: commit_messages
      run: |
        if [ -z "$LAST_TAG" ]; then
          COMMITS=$(git log --oneline)
        else
          COMMITS=$(git log --oneline $LAST_TAG..HEAD)
        fi
        echo "commit_messages=$COMMITS" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag: ${{ github.event.inputs.version }}
        name: Release ${{ github.event.inputs.version }}
        body: |
          ## Changes since ${{ env.last_tag }}
          ${{ env.commit_messages }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
